[theme]
# background = "#000000"
primary = "#FFD6D6"
secondary = "#FFF9F9"
title = "#FA754B"
playing = "#FA754B"
playing_selected = "#FA754B"
playing_bg = "#000000"
highlight = "#FFC583"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#C00606"
statusbar = "#000000"
statusbar_progress = "#FFEDC5"
statusbar_bg = "#FFC67A"
cmdline = "#F9CFC1"
cmdline_bg = "#3E3E3E"
